// Code generated by venom; DO NOT EDIT.
package main

import "github.com/shakefu/venom"

func init() {
	venom.Register(&venom.FuncMeta{
		FullName:    "main.serve_http",
		CommandPath: []string{"serve", "http"},
		Description: "serve over HTTP",
		Params: []venom.ParamMeta{
			{Name: "port", Type: "int", FlagName: "port", Short: "p", Default: "8080", Desc: "port to listen on"},
		},
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.serve_grpc",
		CommandPath: []string{"serve", "grpc"},
		Description: "serve over gRPC",
		Params: []venom.ParamMeta{
			{Name: "port", Type: "int", FlagName: "port", Short: "p", Default: "9090", Desc: "port to listen on"},
		},
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.db_migrate",
		CommandPath: []string{"db", "migrate"},
		Description: "apply pending migrations",
		Params: []venom.ParamMeta{
			{Name: "dryRun", Type: "bool", FlagName: "dry-run", Desc: "print actions without applying them"},
		},
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.db_seedDev",
		CommandPath: []string{"db", "seed-dev"},
		Description: "seed development data",
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.db_reset",
		CommandPath: []string{"db", "reset"},
		Description: "reset the database",
		Params: []venom.ParamMeta{
			{Name: "confirm", Type: "bool", FlagName: "confirm", Desc: "must be true to reset", Required: true},
		},
	})
}
