// Code generated by venom; DO NOT EDIT.
package main

import "github.com/shakefu/venom"

func init() {
	venom.Register(&venom.FuncMeta{
		FullName:    "main.serve",
		CommandPath: []string{"serve"},
		Description: "starts the HTTP server",
		Params: []venom.ParamMeta{
			{Name: "port", Type: "int", FlagName: "port", Short: "p", Default: "8080", Desc: "port to listen on"},
			{Name: "host", Type: "string", FlagName: "host", Default: "localhost", Desc: "host to bind"},
		},
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.initProject",
		CommandPath: []string{"init-project"},
		Description: "initialize a new project",
		Params: []venom.ParamMeta{
			{Name: "dir", Type: "string", FlagName: "dir", Default: ".", Desc: "directory to initialize"},
		},
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.version",
		CommandPath: []string{"version"},
		Description: "show version information",
	})
	venom.Register(&venom.FuncMeta{
		FullName:    "main.copyFiles",
		CommandPath: []string{"copy-files"},
		Description: "copy files to a destination",
		Params: []venom.ParamMeta{
			{Name: "verbose", Type: "bool", FlagName: "verbose", Short: "v", Desc: "enable verbose output"},
		},
		PositionalArgs: []venom.PositionalArgMeta{
			{Name: "src", Type: "string", Position: 0, Cardinality: venom.ArgRequired, Desc: "source file"},
			{Name: "dst", Type: "string", Position: 1, Cardinality: venom.ArgOptional, Default: ".", Desc: "destination directory"},
		},
	})
}
