name: Lint

on:
  pull_request:
  workflow_call:

concurrency:
  group: lint-commits-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@9a9fe03b31c47444290c0d7f9b1ee1b44ee13f20 # v4.1.0
        with:
          command: check
          args: --from-latest-tag --ignore-merge-commits
